<div class="purchase-process-bar has-no-new-paygent">
    <ul class="opc-progress-bar">
        <li class="opc-progress-bar-item first _active">
            <span><?php echo __('Change order contents');?></span>
        </li>

        <li class="opc-progress-bar-item">
            <span><?php echo __('Confirm change contents');?></span>
        </li>

        <li class="opc-progress-bar-item last">
            <span><?php echo __('Change complete');?></span>
        </li>
    </ul>
</div>
<div class="purchase-process-bar has-new-paygent no-display">
    <ul class="opc-progress-bar">
        <li class="opc-progress-bar-item _active">
            <span><?php echo __('Change order contents');?></span>
        </li>

        <li class="opc-progress-bar-item">
            <span><?php echo __('Confirm change contents');?></span>
        </li>

        <li class="opc-progress-bar-item">
            <span><?php echo __('Card information input');?></span>
        </li>

        <li class="opc-progress-bar-item">
            <span><?php echo __('Change complete');?></span>
        </li>
    </ul>
</div>