<?php
/**
 * Add Spot Product
 *
 * @var \Riki\Subscription\Block\Frontend\Profile\AddSpotProduct $block
 */
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
/** @var \Riki\Catalog\Helper\Data $_rikiCatalogHelper */
$_rikiCatalogHelper = $this->helper('Riki\Catalog\Helper\Data');
?>

<div class="search-condition-block">
    <?php echo $this->getChildHtml('searchform') ?>
</div>
<?php if (!$_productCollection->getSize()): ?>
    <div class="search results">
        <div class="toolbar toolbar-products no-result">
            <p class="toolbar-amount"><?php echo __('Displaying 0 of 0') ?></p>
        </div>
        <div class="search-no-result no-result-container">
            <div class="search-no-result message error"><p><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></p></div>
        </div>
        <div class="toolbar toolbar-products no-result">
            <p class="toolbar-amount"><?php echo __('Displaying 0 of 0') ?></p>
        </div>
    </div>
<?php else: ?>
    <div class="search results">
        <?php echo $block->getToolbarHtml() ?>
        <div class="products wrapper grid products-grid">
            <ol class="products list items product-items">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $isNoProductType = $_rikiCatalogHelper->isNoProductType($_product);
                        $deliveryType = $_product->getDeliveryType();
                        $deliveryTypeText = $_rikiCatalogHelper->getLabelHtmlOfDeliveryType($deliveryType);
                        $deliveryTypeHtmlClass = $_rikiCatalogHelper->getLabelHtmlClassOfDeliveryType($deliveryType);
                        $productImage = $block->getImage($_product, 'category_page_grid', ['width' => '100%']);
                        ?>
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $isNoProductType? $_product->getExternalUrl() : $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    $productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                                    echo $_rikiCatalogHelper->truncateHtml($productName, 90, '...');
                                    ?>
                                </a>
                            </strong>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

                            <?php if(!$isNoProductType): ?>
                            <div class="product-item-desc-campaign">
                                <?php /* @escapeNotVerified */
                                $campDescription = $_helper->productAttribute($_product, $_product->getDescriptionCampaign(), 'description_campaign');
                                echo $_rikiCatalogHelper->truncateHtml($campDescription, 13, '...');
                                ?>
                            </div>
                            <div class="product-item-desc">
                                <?php /* @escapeNotVerified */
                                $shortDescription = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                                echo $_rikiCatalogHelper->truncateHtml($shortDescription, 62, '...');
                                ?>
                            </div>
                            <?php endif; ?>

                            <div class="product-tags">
                                <?php if($deliveryType && $deliveryType != 'normal'): ?>
                                    <div class="product-tag delivery_type <?php echo $deliveryTypeHtmlClass; ?>">
                                        <span><?php echo $deliveryTypeText; ?></span>
                                    </div>
                                <?php endif; ?>
                                <?php if($_product->getIsFreeShipping()): ?>
                                    <div class="product-tag free_shipping"><span><?php echo __('Free Shipping') ?></span></div>
                                <?php endif; ?>
                                <?php if($this->helper('\Magento\GiftWrapping\Helper\Data')->isGiftWrappingAvailableForItems() && $_rikiCatalogHelper->hasGiftWrapping($_product)): ?>
                                    <?php if($_rikiCatalogHelper->hasFreeGiftWrapping($_product)): ?>
                                        <div class="product-tag wrapping_available"><span><?php echo __('Wrapping Free') ?></span></div>
                                    <?php else:?>
                                        <div class="product-tag wrapping_available"><span><?php echo __('Wrapping Available') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if($this->helper('\Riki\Preorder\Helper\Data')->getIsProductPreorder($_product)): ?>
                                    <div class="product-tag reorder"><span><?php echo __('Re order') ?></span></div>
                                <?php endif; ?>
                                <?php if($isNoProductType && $_product->getNoProductType()): ?>
                                    <?php if($_product->getNoProductType() == \Riki\Catalog\Model\Config\Source\Product\NoProductType::TYPE_SUBSCRIPTION): ?>
                                        <div class="product-tag subscription"><span><?php echo __('Sub scription') ?></span></div>
                                    <?php endif; ?>
                                    <?php if($_product->getNoProductType() == \Riki\Catalog\Model\Config\Source\Product\NoProductType::TYPE_HANPUKAI): ?>
                                        <div class="product-tag hanpukai"><span><?php echo __('Hanpukai') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="action">
                            <?php if ($_product->isSaleable()) : ?>
                                <?php $postParams = $block->getAddSpotToSubPostParams($_product); ?>
                                <form action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <div class="select-wrapper">
                                        <select title="" name="product_qty" id="product_qty" class="input-new select-box">
                                            <?php for ($i = 1; $i <= 99; $i++) : ?>
                                                <option value="<?php echo $i ?>"><?php echo $i ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                    <input type="hidden" name="product_id" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product_id']; ?>">
                                    <input type="hidden" name="profile_id" value="<?php /* @escapeNotVerified */ echo $block->getProfileId(); ?>">
                                    <button type="submit"><span><?php echo __('Add product to subscription confirmation') ?></span></button>
                                </form>
                            <?php else : ?>
                                <div class="select-wrapper">
                                    <select title="" name="product_qty" id="product_qty" class="input-new select-box" disabled>
                                        <option value="1">1</option>
                                    </select>
                                </div>
                                <div class="button stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                            <?php endif ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>