<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer
 */
/** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer */
?>

<?php $_item = $block->getItem() ?>
<?php $items = array_merge([$_item], $_item->getChildrenItems()); ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>

<?php
/** @var \Riki\Sales\Helper\Admin $helper */
$helper = $this->helper('Riki\Sales\Helper\Admin');
/** @var \Riki\StockPoint\Helper\Data $stockPointHelper */
$stockPointHelper = $this->helper('Riki\StockPoint\Helper\Data');
$canEditAddress = $helper->allowToChangeShippingAddressOfOrderItem($_item)
?>

<?php $_prevOptionId = '' ?>

<?php if($block->getOrderOptions() || $_item->getDescription() || $block->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $unit_qty = (null != $_item->getData('unit_qty'))?$_item->getData('unit_qty'):1;?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_item->getParentItem()): ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product"><div class="option-label"><?php /* @escapeNotVerified */ echo $attributes['option_label'] ?></div></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
        <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?php echo (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?>>
        <?php if (!$_item->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title" id="order_item_<?php /* @escapeNotVerified */ echo $_item->getId() ?>_title">
                <?php echo $block->escapeHtml($_item->getName()) ?>
            </div>
            <div class="product-sku-block">
                <span><?php /* @escapeNotVerified */ echo __('SKU') ?>:</span>
                <?php echo implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))); ?>
            </div>
        </td>
        <?php else: ?>
        <td class="col-product">
            <div class="option-value"><?php echo $block->getValueHtml($_item)?></div>
        </td>
        <?php endif; ?>
        <td class="col-price-original">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?php /* @escapeNotVerified */ echo $helper->getOriginalIncludeTaxByOrderItem($_item); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?php echo $helper->getCatalogDiscountAmountByOrderItem($_item); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <?php if ($stockPointHelper->isStockPointProfileOrder($_item->getOrder())): ?>
            <td class="col-price">
                <?php if ($block->canShowPriceInfo($_item)): ?>
                    <?php echo $helper->getFormatPriceStockPointDiscountAmount($_item); ?>                    &nbsp;
                <?php endif; ?>
            </td>
        <?php endif; ?>
        <td class="col-ordered-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Ordered') ?></th>
                        <?php if('CS' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1/$unit_qty; ?>(<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)</td>
                        <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1 ?>(<?php echo __('EA');?>)</td>
                        <?php  } else {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1 ?></td>
                        <?php  }?>
                    </tr>
                    <?php if ((float) $_item->getQtyInvoiced()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Invoiced') ?></th>
                        <?php if('CS' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyInvoiced()*1/$unit_qty; ?>(<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)</td>
                        <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyInvoiced()*1 ?>(<?php echo __('EA');?>)</td>
                        <?php  } else {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1 ?></td>
                        <?php  }?>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyShipped() && $block->isShipmentSeparately($_item)): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Shipped') ?></th>
                        <?php if('CS' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1/$unit_qty; ?>(<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)</td>
                        <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1 ?>(<?php echo __('EA');?>)</td>
                        <?php  } else {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1 ?></td>
                        <?php  }?>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyRefunded()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Refunded') ?></th>
                        <?php if('CS' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyRefunded()*1/$unit_qty; ?>(<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)</td>
                        <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyRefunded()*1 ?>(<?php echo __('EA');?>)</td>
                        <?php  } else {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyRefunded()*1 ?></td>
                        <?php  }?>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyCanceled()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Canceled') ?></th>
                        <?php if('CS' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyCanceled()*1/$unit_qty; ?>(<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)</td>
                        <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyCanceled()*1 ?>(<?php echo __('EA');?>)</td>
                        <?php  } else {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyCanceled()*1 ?></td>
                        <?php  }?>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($block->isShipmentSeparately($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Ordered') ?></th>
                        <?php if('CS' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1/$unit_qty; ?>(<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)</td>
                        <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1 ?>(<?php echo __('EA');?>)</td>
                        <?php  } else {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered()*1 ?></td>
                        <?php  }?>
                    </tr>
                    <?php if ((float) $_item->getQtyShipped()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Shipped') ?></th>
                        <?php if('CS' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1/$unit_qty ?>(<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)</td>
                        <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1 ?>(<?php echo __('EA');?>)</td>
                        <?php  } else {?>
                            <td><?php /* @escapeNotVerified */ echo $_item->getQtyShipped()*1 ?></td>
                        <?php  }?>
                        </tr>
                    <?php endif; ?>
                </table>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?php echo $block->getColumnHtml($_item, 'subtotal'); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discont">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-wrapping-fee">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('gw_price') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-total">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?php echo $block->getColumnHtml($_item, 'total'); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-rw-earned <?php if(!$canEditAddress): ?>last<?php endif; ?>">
                <?php /* @escapeNotVerified */ echo $helper->generateOrderItemEarnedPointHtml($_item); ?>
        </td>
        <?php if($canEditAddress && !$_item->getParentItem()): ?>
            <td class="col-address last">
                <?php echo $helper->getAddressListByOrderItem($_item); ?>
            </td>
        <?php endif; ?>
    </tr>
<?php endforeach; ?>
<?php if($_showlastRow): ?>
    <tr<?php if (!$block->canDisplayGiftmessage()) echo ' class="border"' ?>>
        <td class="col-product">
            <?php if ($block->getOrderOptions()): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions() as $option): ?>
                    <dt><?php /* @escapeNotVerified */ echo $option['label'] ?>:</dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?php /* @escapeNotVerified */ echo $option['value'];?>
                    <?php else: ?>
                        <?php echo $block->truncateString($option['value'], 55, '', $_remainder);?>
                        <?php if ($_remainder):?>
                            ... <span id="<?php /* @escapeNotVerified */ echo $_id = 'id' . uniqid()?>"><?php /* @escapeNotVerified */ echo $_remainder ?></span>
                            <script>
require(['prototype'], function(){

    $('<?php /* @escapeNotVerified */ echo $_id ?>').hide();
    $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseover', function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').show();});
    $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseout',  function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').hide();});
                            
});
</script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
            <?php echo $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
