<?php
/** @see \Riki\NpAtobarai\Block\Adminhtml\Order\View\Tab\NpTransaction */
?>
<div class="admin__page-section-item">
    <div class="admin__page-section-item-title">
        <span class="title icon-head' "><?php /* @escapeNotVerified */ echo $block->getTabTitle() ?></span>
    </div>
    <div class="admin__page-section-content collected-items">
        <?php echo $block->getChildHtml() ?>
    </div>
</div>