<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div>
    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?php /* @escapeNotVerified */ echo __('Password Help'); ?></span></legend><br/>
        <p class="admin__field-info"><?php /* @escapeNotVerified */ echo __('This function is not available. Please contact administrator'); ?></p>
        <div class="links">
            <a class="action-back" href="<?php /* @escapeNotVerified */ echo $block->getUrl('adminhtml', ['_nosecret' => true]); ?>">
                <?php /* @escapeNotVerified */ echo __('Back to Sign in'); ?>
            </a>
        </div>
    </fieldset>
</div>

