<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="breadcrumbs">
        <ul class="items">
            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <?php if($crumbName !='navigation_path'): ?>
                    <li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                                <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else: ?>
                            <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                <?php else: ?>
                    <?php if($crumbInfo['dataHtml'] !=null): ?>
                        <li class="item navigation_path">
                            <?php echo $crumbInfo['dataHtml']; ?>
                        </li>
                    <?php endif; ?>
                <?php endif; ?>

            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
