<div class="green-contact-block">
    <div class="wrapper-green-contact-block">
        <?php echo $this->getChildHtml('checkout.cart.banner'); ?>
    </div>
</div>
<div class="checkout-cart-back">
    <div class="actions-toolbar">
        <div class="button primary">
            <a href="#" class="action back">
                <span><?php echo __("Go back") ?></span>
            </a>
        </div>
    </div>
</div>