<?php
/**
 * ModuleName
 *
 * PHP version 7
 *
 * @category  RIKI
 * @package   Magento\Rma
 * @author    Nestle.co.jp <support@nestle.co.jp>
 * @copyright 2016 Riki
 * @license   https://opensource.org/licenses/MIT MIT License
 * @link      https://github.com/rikibusiness/riki-ecommerce
 */

// @codingStandardsIgnoreFile

/** @var $block \Riki\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Confirmation */
?>
<div class="admin__page-section-item rma-confirmation">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Return Confirmation') ?></span>
    </div>
    <div class="admin__page-section-item-content order-totals-actions rma-history-form">
        <?php if ($block->canSendConfirmationEmail()): ?>
            <div class="admin__field admin__field-option field-rma-confirmation">
                <input name="rma_confirmation"
                       class="admin__control-checkbox"
                       type="checkbox"
                       id="rma_confirmation"
                       value="1"
                />
                <label class="admin__field-label" for="rma_confirmation">
                    <span><?php /* @escapeNotVerified */ echo __('Email Returns Confirmation') ?></span>
                </label>
            </div>
        <?php endif; ?>
        <?php if ($block->canCreateNewReturn()): ?>
            <div class="actions">
                <button data-mage-init='{"button":{"event":"save","target":"#edit_form"}}'
                        class="action-primary action-save action-default" type="button" id="rma_confirmation_submit">
                    <span><?php /* @escapeNotVerified */ echo __('Submit Returns') ?></span></button>
            </div>
        <?php endif; ?>
    </div>
</div>
