
<?php

// @codingStandardsIgnoreFile

?>

<div data-bind="scope: 'printOrder'">
    <div class="actions">
        <?php  $_order = $block->getOrder() ?>
        <a class="action print" id="opener"  data-trigger="authentication" data-bind="click: function(){ printPopup() }">
            <span><?php /* @escapeNotVerified */ echo __('Print Order') ?></span>
        </a>
        <?php //echo $block->getChildHtml(); ?>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "printOrder": {
                            "component": "Magento_Sales/js/print_order",
                            "template" : "Magento_Sales/print_order",
                            "customVar" : '',
                            "url":"<?php /* @escapeNotVerified */ echo $block->getPrintUrl($_order) ?>"
                        }
                    }
                }
            }
        }
</script>