<?php
/* @var $checkRequestLineAppHelper \Riki\SubscriptionPage\Helper\CheckRequestLineApp */
$checkRequestLineAppHelper = $this->helper('Riki\SubscriptionPage\Helper\CheckRequestLineApp');

/** @var \Riki\Subscription\Block\Multiple\Category\View $block */
$arrSpotProductByCategory = $block->getListOfProductByCategoryOfSummerPage();
?>
<div class="multiple-products-main rk_listProduct" id="adding-spot-subscription"
     data-bind="scope: 'adding-spot-subscription'">
    <?php if ($block->isHasProduct()): ?>
        <div class="note note-bg"><?php echo __('You can check the price for subscription in confirmation page.'); ?></div>
        <div class="subscription_toolbar">
            <div class="subscription_toolbar-label">
                <div class="label-sortby"><?php echo __('Please choose an item from the following.'); ?></div>
            </div>
            <div class="subscription_toolbar-view view-mode pull-right">
                <div class="list-view">
                    <a href="#" class="modes modes-list">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path d="M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z"/>
                            <path d="M0 0h24v24H0z" fill="none"/>
                        </svg>
                    </a>
                    <a href="#" class="modes modes-grid">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
                            <path d="M4 8h4V4H4v4zm6 12h4v-4h-4v4zm-6 0h4v-4H4v4zm0-6h4v-4H4v4zm6 0h4v-4h-4v4zm6-10v4h4V4h-4zm-6 4h4V4h-4v4zm6 6h4v-4h-4v4zm0 6h4v-4h-4v4z"/>
                            <path d="M0 0h24v24H0z" fill="none"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>

        <form class="rk-product-grid category-change-mode"
              action="<?php echo $checkRequestLineAppHelper->getLinkFormAction($block->getUrl('subscriptions/multiple_category/addproduct')); ?>"
              id="form-validate" enctype="multipart/form-data" method="post">
            <input name="form_key" type="hidden" value="<?php echo $block->getAddToCartFormKey(); ?>">
            <input name="riki_profile_id" id="riki_profile_id" type="hidden" value="">
            <input name="campaign_id" id="campaign_id" type="hidden" value="<?php echo $block->getCampaignId(); ?>">
            <?php if (count($arrSpotProductByCategory) > 0): ?>
                <div>
                    <!-- Loop Categories Here -->
                    <?php foreach ($arrSpotProductByCategory as $categoryId => $products): ?>
                        <?php if (count($products) <= 0): continue; endif; ?>
                        <?php $block->getChildBlock('view_category')
                            ->addData([
                                'products' => $products,
                                'category_id' => $categoryId,
                                'category_name' => $block->getCategoryById($categoryId)->getName()
                            ]) ?>
                        <?php echo $block->getChildHtml('view_category', false) ?>
                    <?php endforeach; ?>
                    <!-- End Loop Here -->
                    <div class="subscription-block-bottom">
                        <div class="subscription-pageTop" data-bind="click: moveToTop2">
                            <?php echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('riki-block-pagetop')
                                ->toHtml();
                            ?>
                        </div>
                    </div>
                    <div class="check-offset"></div>
                    <div class="actions-toolbar">
                        <div id="navigation-scroll__nav" class="sub-navigation-scroll hidden">
                            <label data-bind="text: currentSectionName"><?php echo __('Search subscription product by category button') ?> </label>
                            <div class="navigation-select">
                                <select data-bind="value: currentSection, event:{ change: navigationScroll }">
                                    <option value=""><?php echo __('Search subscription product by category button') ?></option>
                                    <?php foreach ($arrSpotProductByCategory as $categoryId => $products): ?>
                                        <?php if (empty($products)): continue; endif; ?>
                                        <option value="section-<?php echo $categoryId ?>"><?php echo $block->getCategoryById($categoryId)->getName() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="primary">
                            <div class="total-amount-block hidden">
                                <table class="table table-total-amount">
                                    <tr>
                                        <td class="mask"
                                            data-label="<?php echo $block->escapeHtml(__('(Incl. Tax)')); ?>"><?php echo __('Total Amount') ?></td>
                                        <td class="value" id="total-amount">0円</td>
                                    </tr>
                                </table>
                            </div>
                            <button type="button"
                                    title="<?php echo __('Add spot to subscription'); ?>"
                                    class="action submit primary to-subscription"
                                    disabled="disabled"
                                    data-bind="click: openPopup">
                                <span><?php echo __('Add spot to subscription'); ?></span>
                            </button>
                            <!-- ko foreach:getRegion('profile-information') -->
                            <!-- ko template: getTemplate() --><!-- /ko -->
                            <!-- /ko -->
                        </div>
                        <div class="secondary"></div>
                    </div>
                </div>

                <script type="text/x-magento-init">
                {
                    "#adding-spot-subscription": {
                        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
                    echo $block->getJsLayout(); ?>
                    },
                    "*": {
                        "Magento_Catalog/js/unsticky-cart": {}
                    }
                }

                </script>
                <script type="text/javascript">
                    window.multileCategoryCampaignConfig = <?php /* @escapeNotVerified */ echo $block->getConfig(); ?>;
                </script>

                <script type="text/javascript">
                    require([
                        'jquery',
                        'mage/mage',
                        'Magento_Catalog/product/view/validation',
                        'Magento_Catalog/js/catalog-add-to-cart',
                        // 'Riki_Subscription/js/multiple/category/campaign/view/calculate-price'
                    ], function ($) {
                        'use strict';
                        $('#form-validate').mage('validation', {
                            radioCheckboxClosest: '.nested'
                        });
                    });
                </script>
                <script type="text/x-magento-init">
                    {
                        "#adding-spot-subscription": {
                           "Magento_Ui/js/core/app": {
                               "components": {
                                    "multipleCategoryCampaignSelectedProducts": {
                                        "component": "Riki_Subscription/js/multiple/category/campaign/view/subscription-multiple-category"
                                   },
                                   "imageLazyLoad": {
                                       "component": "Riki_Catalog/js/catalog/image-lazy-loading"
                                   }
                               }
                            }
                       }
                    }

                </script>
            <?php endif; ?>
        </form>
    <?php else: ?>
        <div class="note">
            <?php echo __('There are something wrong via the system. Please contact our call center for helping.') ?>
        </div>
    <?php endif; ?>

    <?php echo $block->render('Riki_SubscriptionPage::view/product-detail.phtml', []) ?>
</div>