<?php
// @codingStandardsIgnoreFile
?>
<?php $block->setPriceDataObject($block->getSource()) ?>

<?php if ((float) $block->getSource()->getUsedPointAmount()): ?>
    <tr>
        <td class="label"><?php /* @escapeNotVerified */ echo __('Point Used') ?></td>
        <td>
            <?php /* @escapeNotVerified */ echo $block->displayPrices($block->getSource()->getBaseRewardCurrencyAmount(), $block->getSource()->getUsedPointAmount()); ?>
        </td>
    </tr>
<?php endif; ?>
