<?php
namespace Riki\Subscription\Block\Adminhtml\Order\Create;

/**
 * Adminhtml sales order create search block
 *
 * @author      Magento Core Team <core@magentocommerce.com>
 */
class Machines extends \Magento\Sales\Block\Adminhtml\Order\Create\AbstractCreate
{
    /**
     * Constructor
     *
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setId('sales_order_create_machines');
    }

    /**
     * Get header text
     *
     * @return \Magento\Framework\Phrase
     */
    public function getHeaderText()
    {
        return __('Please select machines');
    }

    /**
     * Get buttons html
     *
     * @return string
     */
    public function getButtonsHtml()
    {
        $addButtonAdd = [
            'label' => __('Add Selected Product(s) to Order'),
            'onclick' => 'order.machinesGridAddSelected(this)',
            'class' => 'action-add action-secondary',
        ];
        $backButtonData = [
            'label' => __('Back'),
            'onclick' => 'addBySku.closeGridMachineTypes()',
            'class' => 'action-add action-secondary',
        ];
        $button = $this->getLayout()->createBlock(
            \Magento\Backend\Block\Widget\Button::class
        )->setData(
            $addButtonAdd
        )->toHtml();
        $button .= $this->getLayout()->createBlock(
            \Magento\Backend\Block\Widget\Button::class
        )->setData(
            $backButtonData
        )->toHtml();
        return $button;
    }

    /**
     * Get header css class
     *
     * @return string
     */
    public function getHeaderCssClass()
    {
        return 'head-catalog-product';
    }
    
    public function getProductCourseUrl()
    {
        return $this->getUrl('profile/product/saveCourse'); // TODO: Change the autogenerated stub
    }
}
