<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Riki\Subscription\Block\Adminhtml\Order\Create;

/**
 * Adminhtml sales order create search block
 *
 * @author      Magento Core Team <core@magentocommerce.com>
 */
class Product extends \Magento\Sales\Block\Adminhtml\Order\Create\AbstractCreate
{
    /**
     * @var \Riki\SubscriptionCourse\Model\ResourceModel\Course
     */
    protected $subscriptionModel;
    /**
     * @var \Riki\SubscriptionPage\Helper\Data
     */
    protected $subscriptionPageHelper;
    public function __construct
    (
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Model\Session\Quote $sessionQuote,
        \Magento\Sales\Model\AdminOrder\Create $orderCreate,
        \Magento\Framework\Pricing\PriceCurrencyInterface $priceCurrency,
        \Riki\SubscriptionCourse\Model\ResourceModel\Course $subscriptionModel,
        \Riki\SubscriptionPage\Helper\Data $helperSubPage,
        array $data = []
    )
    {
        $this->subscriptionModel = $subscriptionModel;
        $this->subscriptionPageHelper = $helperSubPage;
        parent::__construct($context, $sessionQuote, $orderCreate, $priceCurrency, $data);
    }

    /**
     * Constructor
     *
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setId('sales_order_create_product_course');
    }

    /**
     * Get header text
     *
     * @return \Magento\Framework\Phrase
     */
    public function getHeaderText()
    {
        return __('Please select products');
    }

    /**
     * Get buttons html
     *
     * @return string
     */
    public function getButtonsHtml()
    {
        $addButtonAdd = [
            'label' => __('Add Selected Product(s) to Order'),
            'onclick' => 'order.productCourseGridAddSelected(this)',
            'class' => 'action-add action-secondary',
        ];
        $addButtonBack = [
            'label' => __('Back'),
            'onclick' => 'order.backCourse()',
            'class' => 'action-add action-secondary',
        ];
        $button = $this->getLayout()->createBlock(
            'Magento\Backend\Block\Widget\Button'
        )->setData(
            $addButtonAdd
        )->toHtml();
        $button .= $this->getLayout()->createBlock(
            'Magento\Backend\Block\Widget\Button'
        )->setData(
            $addButtonBack
        )->toHtml();

        return $button;
    }

    /**
     * Get header css class
     *
     * @return string
     */
    public function getHeaderCssClass()
    {
        return 'head-catalog-product';
    }
    public function _prepareLayout()
    {
        $this->addChild('additional_product', 'Riki\Subscription\Block\Adminhtml\Order\Create\Additional\Grid');
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
    public function checkCourseHasAdditionalCategory(){
        $courseId = $this->getRequest()->getParam('id');
        $subscriptionType = $this->subscriptionPageHelper->getSubscriptionType($courseId);
        $isHanpukai = ($subscriptionType=='hanpukai')?true:false;
        if($isHanpukai){
            return false;
        }
        $storeId = $this->_sessionQuote->getQuote()->getStore()->getId();
        $collection = $this->subscriptionModel->getAllProductByCoursePieceCase($courseId,$storeId,null,true);
        if($collection != false and $collection->getSize() > 0){
            return true;
        }
        return false;
    }

}
