<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magento\Tax\Block\Checkout\Grandtotal
 * @see \Magento\Tax\Block\Checkout\Grandtotal
 */
?>
<?php if ($block->includeTax() && $block->getTotalExclTax() >= 0):?>
    <tr class="row-totals">
        <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-mark" colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>">
            <strong><?php /* @escapeNotVerified */ echo __('Grand Total Incl. Tax')?></strong>
        </td>
        <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-amount">
            <strong><?php /* @escapeNotVerified */ echo $block->formatPrice($block->getTotal()->getValue()) ?></strong>
        </td>
    </tr>
<?php else:?>
    <tr class="row-totals">
        <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-mark" colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>">
            <strong><?php /* @escapeNotVerified */ echo $block->getTotal()->getTitle() ?></strong>
        </td>
        <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-amount">
            <strong><?php /* @escapeNotVerified */ echo $block->formatPrice($block->getTotal()->getValue()) ?></strong>
        </td>
    </tr>
<?php endif;?>
