<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-shipment-table">
        <thead>
        <tr class="headings">
            <th class="col-product"><span><?= /* @escapeNotVerified */  __('Product') ?></span></th>
            <th class="col-subtotal"><span><?= /* @escapeNotVerified */  __('Purchased Amount (Incl. Tax)') ?></span></th>
            <th class="col-qty "><span><?= /* @escapeNotVerified */  __('Qty Shipped') ?></span></th>
            <th class="col-commission_amount last"><span><?= /* @escapeNotVerified */  __('Commission Amount') ?></span></th>
        </tr>
        </thead>
        <?php $_items = $block->getShipment()->getAllItems() ?>
        <?php $_i = 0; foreach ($_items as $_item): if ($_item->getOrderItem()->getParentItem()): continue; endif; $_i++ ?>
            <tbody class="<?= /* @escapeNotVerified */ $_i%2 ? 'odd' : 'even' ?>">
            <?= $block->getItemHtml($_item) ?>
            <?= $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
