
<div class="entry-edit fieldset" id="import_validation_container" style="display:none;">
    <div class="entry-edit-head legend">
        <span class="icon-head head-edit-form fieldset-legend"
            id="import_validation_container_header"><?php /* @escapeNotVerified */ echo __('Validation Results'); ?></span>
    </div><br>
    <div id="import_validation_messages" class="fieldset"><!-- --></div>
</div>
