<?php

namespace Riki\Loyalty\Block\Adminhtml\Sales\Order;

class Approve extends \Magento\Backend\Block\Template
{
    protected $_template = 'Riki_Loyalty::sales/order/approve.phtml';

    /**
     * @var \Magento\Framework\Registry
     */
    protected $_registry;

    public function __construct(
        \Magento\Framework\Registry $registry,
        \Magento\Backend\Block\Template\Context $context,
        array $data = []
    )
    {
        parent::__construct($context, $data);
        $this->_registry = $registry;
    }

    /**
     * @return \Magento\Sales\Model\Order
     */
    public function getOrder()
    {
        return $this->_registry->registry('current_order');
    }

    /**
     * @return string
     */
    protected function _toHtml()
    {
        if (!$this->_authorization->isAllowed('Riki_Loyalty::approve_point')) {
            return '';
        }
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}