<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Bundle\Pricing\Render\FinalPriceBox $block */
$productId = $block->getSaleableItem()->getId();
/** @var \Magento\Bundle\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPrice();
$minimalPrice = $finalPriceModel->getMinimalPrice();
$maximalPrice = $finalPriceModel->getMaximalPrice();
/** @var \Magento\Bundle\Pricing\Price\BundleRegularPrice $regularPriceModel */
$regularPriceModel = $block->getPriceType('regular_price');
$maximalRegularPrice = $regularPriceModel->getMaximalPrice();
$minimalRegularPrice = $regularPriceModel->getMinimalPrice();
?>
<?php if ($block->getSaleableItem()->getPriceView()): ?>
    <p class="minimal-price">
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'display_label'     => __('As low as'),
                'price_id'          => $block->getPriceId('from-'),
                'include_container' => true
            ]); ?>
        </span>
    </p>
<?php else: ?>
    <?php if ($block->showRangePrice()): ?>
        <p class="price-from">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'display_label'     => __('From'),
                'price_id'          => $block->getPriceId('from-'),
                'price_type'        => 'minPrice',
                'include_container' => true
            ]); ?>
        </p>
        <p class="price-to">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($maximalPrice, [
                'display_label'     => __('To'),
                'price_id'          => $block->getPriceId('to-'),
                'price_type'        => 'maxPrice',
                'include_container' => true
            ]); ?>
        </p>
    <?php else: ?>
        <span class="minimal-price-link<?php if ($minimalPrice < $minimalRegularPrice): ?> has-old-price<?php endif; ?>">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'price_id'          => $block->getPriceId('product-price-'),
                'include_container' => true,
                'price_type'        => 'mainPrice',
            ]); ?>
        </span>
    <?php endif ?>
<?php endif ?>
