<?php
namespace Riki\Rma\Model\ResourceModel;

use Magento\Framework\App\ResourceConnection;

class Grid extends \Magento\Rma\Model\ResourceModel\Grid
{
    /**
     * @param \Magento\Framework\Model\AbstractModel $object
     * @return $this
     */
    protected function _beforeSave(\Magento\Framework\Model\AbstractModel $object)
    {
        if (!$object->getData('rma_shipment_number')) {
            $object->setData('shipment_status', null);
        }

        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }

    /**
     * Get connection
     *
     * @return \Magento\Framework\DB\Adapter\AdapterInterface|false
     */
    public function getConnection()
    {
        return $this->_resources->getConnection(ResourceConnection::DEFAULT_CONNECTION);
    }

    /**
     * @param $paymentStatus
     * @param array $orderIds
     * @return $this
     */
    public function updatePaymentStatusByOrderId($paymentStatus, array $orderIds)
    {
        $this->getConnection()->update(
            $this->getMainTable(),
            ['payment_status' => $paymentStatus],
            ['order_id IN(?)' => $orderIds]
        );

        return $this;
    }

    /**
     * @param \Magento\Sales\Model\Order $order
     * @return $this
     */
    public function updatePaymentStatusByOrder(\Magento\Sales\Model\Order $order)
    {
        $orderId = $order->getId();
        $paymentStatus = $order->getPaymentStatus();

        $this->getConnection()->update(
            $this->getMainTable(),
            ['payment_status' => $paymentStatus],
            ['order_id=?' => $orderId]
        );

        return $this;
    }
}
