<?php
namespace Riki\Rma\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class ReviewCc extends AbstractDb
{
    /**
     * {@inheritdoc}
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('riki_rma_review_cc', 'entity_id');
    }

    /**
     * @param \Magento\Framework\Model\AbstractModel $object
     * @return $this
     */
    protected function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {
        $returns = $object->getReturnsData();

        if ($returns) {

            $savedData = [];

            /** @var \Magento\Rma\Model\Rma $return */
            foreach ($returns as $return) {
                $savedData[] = [
                    'rma_id'    =>  $return->getId(),
                    'review_id' =>  $object->getId()
                ];
            }

            $this->getConnection()->insertOnDuplicate($this->getTable('riki_rma_review_cc_item'), $savedData);
        }

        return parent::_afterSave($object); // TODO: Change the autogenerated stub
    }
}
