<?php foreach ($block->getData('items') as $key => $item): ?>
-------------------------------------------------------------------------------
<?php echo __('【oos id】 %1', $item['oosId']) . "\n" ?>
<?php echo __('【transaction id】 %1', $item['tradingId']) . "\n" ?>
<?php echo __('【customer id】 %1', $item['consumerId']) . "\n" ?>
<?php echo __('【subscription course name】 %1', $item['subscriptionCourseName']) . "\n" ?>
<?php echo __('【error message】 %1', $item['errorMessage']) . "\n" ?>
<?php endforeach; ?>
