<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer */ ?>

<?php $_item = $block->getItem() ?>
<?php $qty = $_item->getQty() ?>
<?php $commissionAmount = $_item->getCommissionAmount() ?>
<?php $items = array_merge([$_item->getOrderItem()], $_item->getOrderItem()->getChildrenItems()) ?>
<?php $shipItems = $block->getChildren($_item);

?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $_item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php
/** @var \Magento\Sales\Model\Order\Item $_item */
foreach ($items as $_item):
    ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product"><div class="option-label"><?php /* @escapeNotVerified */ echo $attributes['option_label'] ?></div></td>
            <td>&nbsp</td>
            <td class="col-qty">&nbsp</td>
            <td class="last">&nbsp;</td>
        </tr>
        <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?php echo(++$_index == $_count && !$_showlastRow) ? ' class="border"' : '' ?>>
        <?php if (!$_item->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title"><?php echo $block->escapeHtml($_item->getName()) ?></div>
            <div class="product-sku-block">
                <span><?php /* @escapeNotVerified */ echo __('SKU') ?>:</span>
                <?php echo implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))); ?>
            </div>
        </td>
        <?php else: ?>
        <td class="col-product"><div class="option-value"><?php echo $block->getValueHtml($_item)?></div></td>
        <?php endif; ?>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col-subtotal"><?php echo $_item->getOrder()->formatPrice($_item->getPriceInclTax() * $qty) ?></td>
        <?php else: ?>
            <td class="col-subtotal"></td>
        <?php endif; ?>

        <td class="col-qty">
            <?php if (($block->isShipmentSeparately() && $_item->getParentItem()) || (!$block->isShipmentSeparately() && !$_item->getParentItem())): ?>
                <?php if (isset($shipItems[$_item->getId()])): ?>
                    <?php if(\Riki\CreateProductAttributes\Model\Product\CaseDisplay::PROFILE_UNIT_CASE == $_item->getData('unit_case')) {?>
                        <?php $unit_qty = (null != $_item->getData('unit_qty'))?$_item->getData('unit_qty'):1;?>
                        <?php /* @escapeNotVerified */ echo $shipItems[$_item->getId()]->getQty()*1 / $unit_qty; ?> (<?php echo __('CS').' ('.$unit_qty.' '.__('EA').')';?>)
                    <?php  } elseif('EA' == $_item->getData('unit_case')) {?>
                        <?php /* @escapeNotVerified */ echo $shipItems[$_item->getId()]->getQty()*1 ?>(<?php echo __('EA');?>)
                    <?php  } else {?>
                        <?php /* @escapeNotVerified */ echo $shipItems[$_item->getId()]->getQty()*1 ?>
                    <?php  }?>
                <?php elseif ($_item->getIsVirtual()): ?>
                    <?php /* @escapeNotVerified */ echo __('N/A') ?>
                <?php else: ?>
                    0
                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col-commission_amount last"><?php echo $_item->getOrder()->formatPrice($commissionAmount); ?></td>
        <?php else: ?>
            <td class="col-commission_amount last"></td>
        <?php endif; ?>

    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions($_item->getOrderItem())): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions($_item->getOrderItem()) as $option): ?>
                    <dt><?php /* @escapeNotVerified */ echo $option['label'] ?></dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?php /* @escapeNotVerified */ echo $option['value'];?>
                    <?php else: ?>
                        <?php echo $block->truncateString($option['value'], 55, '', $_remainder);?>
                        <?php if ($_remainder):?>
                            ... <span id="<?php /* @escapeNotVerified */ echo $_id = 'id' . uniqid()?>"><?php /* @escapeNotVerified */ echo $_remainder ?></span>
                            <script>
require(['prototype'], function(){

                            $('<?php /* @escapeNotVerified */ echo $_id ?>').hide();
                            $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseover', function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').show();});
                            $('<?php /* @escapeNotVerified */ echo $_id ?>').up().observe('mouseout',  function(){$('<?php /* @escapeNotVerified */ echo $_id ?>').hide();});

});
</script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php echo $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td>&nbsp</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
