<div class="cvspayment-mess-left">
    <div data-bind="i18n: 'We send you a transfer form before shipping out your order. Please pay at convenience store within the period.'"></div>
    <div data-bind="i18n: 'The transfer form will be delivered after 4 days from order complete.'"></div>
    <div data-bind="i18n: 'The due date will be 10 days after issuing date.'"></div>
    <div data-bind="i18n: 'Also, please make sure to finish your payment in 30 days, otherwise your order will be cancelled.'"></div>
</div>
<div class="cvspayment-mess-right">
    <img alt="cvs-payment-form" src="<?= $block->getViewFileUrl('images/cvs-payment-form.jpg') ?>" />
</div>