<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_giftWrappingAvailable = $this->helper('\Magento\GiftWrapping\Helper\Data')->isGiftWrappingAvailableForItems();
/** @var \Riki\Catalog\Helper\Data $_rikiCatalogHelper */
$_rikiCatalogHelper = $this->helper('Riki\Catalog\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid" data-item-id="<?php echo $_product->getSku();?>">
                    <?php
                    $isNoProductType = $_rikiCatalogHelper->isNoProductType($_product);
                    $deliveryType = $_product->getDeliveryType();
                    $deliveryTypeText = $_rikiCatalogHelper->getLabelHtmlOfDeliveryType($deliveryType);
                    $deliveryTypeHtmlClass = $_rikiCatalogHelper->getLabelHtmlClassOfDeliveryType($deliveryType);
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a layer-item-id="<?php echo $_product->getId();?>" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details" data-item-id="<?php echo $_product->getSku();?>">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               layer-item-id="<?php echo $_product->getId();?>"
                               title = "<?php /* @escapeNotVerified */ echo $block->escapeHtml($_product->getName()); ?>"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $block->escapeHtml($_product->getName()); ?>
                            </a>
                        </strong>
                        <div class="product-item-desc">
                            <?php /* @escapeNotVerified */
                            $shortDescription = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                            echo $this->helper('Riki\Catalog\Helper\Data')->subStrHtml($shortDescription, 0, 130);
                            ?>
                        </div>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-tags">
                            <?php if($deliveryType): ?>
                                <div class="product-tag delivery_type <?php echo $deliveryTypeHtmlClass; ?>">
                                    <span><?php echo __($deliveryTypeText); ?></span>
                                </div>
                            <?php endif; ?>
                            <?php if($_product->getIsFreeShipping()): ?>
                                <div class="product-tag free_shipping"><span><?php echo __('Free Shipping') ?></span></div>
                            <?php endif; ?>
                            <?php if($_giftWrappingAvailable && $_rikiCatalogHelper->hasGiftWrapping($_product)): ?>
                                <?php if($_rikiCatalogHelper->hasFreeGiftWrapping($_product)): ?>
                                    <div class="product-tag wrapping_available"><span><?php echo __('Wrapping Free') ?></span></div>
                                <?php else:?>
                                    <div class="product-tag wrapping_available"><span><?php echo __('Wrapping Available') ?></span></div>
                                <?php endif; ?>
                            <?php endif; ?>
                            <div class="product-tag reorder"><span><?php echo __('Reorder') ?></span></div>
                            <div class="product-tag subscription"><span><?php echo __('Subscription') ?></span></div>
                            <div class="product-tag hanpukai"><span><?php echo __('Hanpukai') ?></span></div>
                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php
                                        $postParams = $block->getAddToCartPostParams($_product);
                                        $button_title = $this->helper('Riki\Preorder\Helper\Data')->getAddToCartLabel( $_product );//
                                        if (empty($button_title))
                                        {
                                            $button_title = __('Add To Cart');
                                        }
                                        $button_mobile_title = $this->helper('Riki\Preorder\Helper\Data')->getAddToCartLabel( $_product, true );
                                        if (empty($button_mobile_title))
                                        {
                                            $button_mobile_title = __('Buy');
                                        }
                                        $button_class = $this->helper('Riki\Preorder\Helper\Data')->getAddToCartClass($_product);
                                        ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="productpage" value="listing" class="input-text" />
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <input type="number" name="qty" maxlength="3" value="<?php /* @escapeNotVerified */ echo $block->getMinimalQty($_product) ?>" class="input-text qty">
                                            <button type="submit"
                                                    title="<?php echo $button_title; ?>"
                                                    default-title="<?php echo $button_title; ?>"
                                                    class="action tocart primary btn-pc <?php echo $button_class;?>">
                                                <span><?php /* @escapeNotVerified */ echo $button_title; ?></span>
                                            </button>
                                            <button type="submit"
                                                    title="<?php echo $button_mobile_title; ?>"
                                                    default-title="<?php echo $button_mobile_title; ?>"
                                                    class="action tocart primary btn-mb <?php echo $button_class;?>">
                                                <span><?php /* @escapeNotVerified */ echo $button_mobile_title;?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <input type="number" name="qty" maxlength="3" value="<?php /* @escapeNotVerified */ echo $block->getMinimalQty($_product) ?>" class="input-text qty" />
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>

                                            <input type="number" name="qty" maxlength="3" value="<?php /* @escapeNotVerified */ echo $block->getMinimalQty($_product) ?>" class="input-text qty" />
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $(document).ready(function () {
            var addButton = $('.products.wrapper .action.tocart');

            addButton.on('click', function () {
                var _this = $(this),
                    qty = _this.prev('.qty').val();
                if(isNaN(qty) || qty <= 0)
                    return false;
            });
        });
    });
</script>
