<tr class="row-totals">
    <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-mark" colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>">
        <?php /* @escapeNotVerified */ echo $block->getTotal()->getTitle() ?>
    </td>
    <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-amount">
        <?php /* @escapeNotVerified */ echo $block->getTotal()->getValue() . __('point(s)') ?>
    </td>
</tr>