<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\PriceBox $block */

/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $block->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
$msrpShowOnGesture = $block->getPriceType('msrp_price')->isShowPriceOnGesture();
$product = $block->getSaleableItem();
$hasTierPrice = (count($tierPrices)) ? 1 : 0;
$minTierPrice = null;
?>
<?php if ($hasTierPrice) : ?>
    <ul class="<?php /* @escapeNotVerified */ echo($block->hasListClass() ? $block->getListClass() : 'prices-tier items'); ?>">
        <?php foreach ($tierPrices as $index => $price) : ?>
            <li class="item">
                <?php
                $productId = $product->getId();
                $caseDisplay = $product->getCaseDisplay();
                $unitCase = 'EA';
                $unitQty = 1;
                if($caseDisplay ==2 ){
                    $unitCase = 'CS';
                    $unitQty = (null != $product->getUnitQty())?$product->getUnitQty():1;
                }

                $isSaleable = $product->isSaleable();
                $popupId = 'msrp-popup-' . $productId . $block->getRandomString(20);
                if ($msrpShowOnGesture && $price['price']->getValue() < $product->getMsrp()):
                    $addToCartUrl = '';
                    if ($isSaleable) {
                        $addToCartUrl = $this->helper('\Magento\Checkout\Helper\Cart')
                            ->getAddUrl($product, ['qty' => $price['price_qty']]);
                    }
                    $tierPriceData = [
                        'addToCartUrl' => $addToCartUrl,
                        'name' => $product->getName(),
                        'realPrice' => $block->renderAmount(
                            $price['price'],
                            [
                                'price_id'          => $index,
                                'id_suffix'         => '-' . $index,
                                'include_container' => true
                            ]
                        ),
                        'msrpPrice' => $block->renderAmount(
                            $block->getPriceType('msrp_price')->getAmount(),
                            [
                                'price_id'          => $index,
                                'id_suffix'         => '-' . $index,
                                'include_container' => true
                            ]
                        ),
                    ];
                    if ($block->getCanDisplayQty($product)) {
                        $tierPriceData['qty'] = $price['price_qty'];
                    }
                    ?>
                    <?php /* @escapeNotVerified */ echo __('Buy %1 for: ', $price['price_qty']); ?>
                    <a href="javascript:void(0);"
                       id="<?php /* @escapeNotVerified */ echo($popupId);?>"
                       data-tier-price="<?php echo $block->escapeHtml($block->jsonEncode($tierPriceData)); ?>">
                        <?php /* @escapeNotVerified */ echo __('Click for price'); ?></a>
                <?php else:
                    $priceAmountBlock = $block->renderAmount(
                        $price['price'],
                        [
                            'price_id'          => $index,
                            'id_suffix'         => '-' . $index,
                            'include_container' => true,
                            'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_OPTION
                        ]
                    );
                    ?>
                    <?php /* @escapeNotVerified */

                    if('CS' == $unitCase){
                        echo ($block->getShowDetailedPrice() !== false)
                            ? __(
                                '%1 ケース: %2 / %3',
                                ceil($price['price_qty']/$unitQty),
                                $priceAmountBlock,
                                __($unitCase)
                            )
                            : __('%1 ケース: %2 / %3', ceil($price['price_qty']/$unitQty), $priceAmountBlock,__($unitCase));
                    }
                    else
                    if('EA' == $unitCase){
                        echo ($block->getShowDetailedPrice() !== false)
                            ? __(
                                '%1 個セット: %2 / %3',
                                ceil($price['price_qty']/$unitQty),
                                $priceAmountBlock,
                                __($unitCase)
                            )
                            : __('%1 個セット: %2 / %3', ceil($price['price_qty']/$unitQty), $priceAmountBlock,__($unitCase));
                    }
                    else{
                        echo ($block->getShowDetailedPrice() !== false)
                            ? __(
                                'Buy %1 or more: %2 / set',
                                $price['price_qty'],
                                $priceAmountBlock
                            )
                            : __('Buy %1 or more: %2 / set', $price['price_qty'], $priceAmountBlock);
                    }

                    ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php if ($msrpShowOnGesture):?>
        <script type="text/x-magento-init">
            {
                ".product-info-main": {
                    "addToCart": {
                        "origin": "tier",
                        "addToCartButton": "#product_addtocart_form [type=submit]",
                        "inputQty": "#qty",
                        "attr": "[data-tier-price]",
                        "productForm": "#product_addtocart_form",
                        "productId": "<?php /* @escapeNotVerified */ echo $productId; ?>",
                        "productIdInput": "input[type=hidden][name=product]",
                        "isSaleable": "<?php /* @escapeNotVerified */ echo $isSaleable; ?>"
                    }
                }
            }
        </script>
    <?php endif;?>
<?php endif; ?>
<script type="text/javascript">
    var tierPriceObj_<?php echo $product->getId() ?> = {
        hasTierPrice: <?php echo $hasTierPrice ?>,
        tierPriceItem: []
    };
    <?php foreach ($tierPrices as $price) : ?>
    tierPriceObj_<?php echo $product->getId() ?>.tierPriceItem.push({
        qty: <?php echo $price['price_qty'] ?>,
        price: <?php echo $price['price'] ?>
    });
    <?php $minTierPrice = ($minTierPrice === null || $minTierPrice > $price['price']) ? $price['price'] : $minTierPrice ?>
    <?php endforeach; ?>

    tierPriceObj_<?php echo $product->getId() ?>['minTierPrice'] = <?=  $minTierPrice?: 0  ?>;
</script>
