<?php /** @var $block \Riki\FairAndSeasonalGift\Block\Adminhtml\Fair\Edit\Tab\Related\Tab */ ?>

<div class="admin__page-section-item">
    <div class="admin__page-section-item-title">
        <span class="title <?php echo($block->getHeaderCssClass()) ? $block->getHeaderCssClass() . ' icon-head' : '' ?>"><?php /* @escapeNotVerified */ echo $block->getHeaderText() ?></span>
    </div>
    <div class="admin__page-section-content fair-items">
        <?php echo $block->getChildHtml('', true) ?>
    </div>
</div>
