<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="import-export-tax-rates">
    <div class="import-tax-rates">
        <?php if ($block->getUseContainer()): ?>
        <form id="import-form" class="admin__fieldset" action="<?php /* @escapeNotVerified */ echo $block->getUrl('rikiship/shipment/importPost') ?>" method="post" enctype="multipart/form-data">
        <?php endif; ?>
            <?php echo $block->getBlockHtml('formkey')?>
            <!-- import file for shippped out -->
            <h3><?php echo __('Upload shipped out CSV files') ?></h3>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse TOYO file - 1501') ?></span>
                <br/>
                    <span>(Ex: XTXR1501_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1501" name="import_1501" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse ASKUL file - 1601') ?></span>
                    <br/>
                    <span>(Ex: XBXR1601_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1601" name="import_1601" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label  class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse HITACH file - 1701') ?></span>
                    <br/>
                    <span>(Ex: XHXR1701_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1701" name="import_1701" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse LOGICALPLANT') ?></span>
                    <br/>
                    <span>(Ex: LOGICALPLANT_SHIP_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1801" name="import_1801" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse WH5 file') ?></span>
                    <br/>
                    <span>(Ex: WAREHOUSE5_SHIP_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1901" name="import_1901" class="input-file"/>
                </div>
            </div>
            <hr/>
            <!-- end of shipped out -->
            <h3><?php echo __('Upload delivery complete CSV files') ?></h3>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse TOYO File - 1502') ?></span>
                    <br/>
                    <span>(Ex: XTXR1502_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1502" name="import_1502" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse ASKUL File - 1602') ?></span>
                    <br/>
                    <span>(Ex: XBXR1602_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1602" name="import_1602" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse HITACHI-TS-TS File - 1702') ?></span>
                    <br/>
                    <span>(Ex: XHXR1702_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1702" name="import_1702" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse LOGICALPLANT File') ?></span>
                    <br/>
                    <span>(Ex: LOGICALPLANT_DELIVERY_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1802" name="import_1802" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse WH5 File') ?></span>
                    <br/>
                    <span>(Ex: WAREHOUSE5_DELIVERY_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1902" name="import_1902" class="input-file"/>
                </div>
            </div>
            <hr/>
            <!-- end of delivery complete -->
            <h3><?php echo __('Upload COD Payment collection CSV files') ?></h3>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse TOYO File - 1504') ?></span>
                    <br/>
                    <span>(Ex: XTXR1504_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1504" name="import_1504" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse BIZEX File - 1604') ?></span>
                    <br/>
                    <span>(Ex: XBXR1604_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1604" name="import_1604" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse HITACHI-TS File - 1704') ?></span>
                    <br/>
                    <span>(Ex: XHXR1704_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1704" name="import_1704" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse LOGICALPLANT File') ?></span>
                    <br/>
                    <span>(Ex: LOGICALPLANT_COD_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1804" name="import_1804" class="input-file"/>
                </div>
            </div>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Warehouse WH5 File') ?></span>
                    <br/>
                    <span>(Ex: WAREHOUSE5_COD_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1904" name="import_1904" class="input-file"/>
                </div>
            </div>
            <hr/>
            <h3><?php echo __('Upload CVS Payment collection CSV files') ?></h3>
            <div class="fieldset admin__field">
                <label class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Money Collection By CVS - 1507') ?></span>
                    <br/>
                    <span>(Ex: XTXR1507_2018.csv)</span>
                </label>
                <div class="admin__field-control">
                    <input type="file" id="import_1507" name="import_1507" class="input-file"/>
                </div>
            </div>
            <hr/>
            <br/>
            <div class="fieldset admin__field">
                <label class="admin__field-label"></label>
                <div class="admin__field-control">
                    <?php echo $block->getButtonHtml(__('Upload Shipments'), '', 'import-submit') ?>
                </div>
            </div>
        <?php if ($block->getUseContainer()): ?>
        </form>
        <script>
            require(['jquery', "mage/mage", "loadingPopup"], function(jQuery){

                jQuery('#import-form').mage('form').mage('validation');
                (function ($) {
                    $('.import-submit').click(function(){
                            $(this.form).submit();
                    });
                })(jQuery);

            });
        </script>
        <?php endif; ?>
    </div>
</div>
