<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Tax\Block\Item\Price\Renderer */

$_item = $block->getItem();
$unitConvert = 1;
if($_item->getUnitCase() == 'CS'){
    $unitConvert = $_item->getUnitQty();
    $unitConvert = ($unitConvert != null && $unitConvert > 0)?$unitConvert:1;
}
?>

<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
    <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax')); ?>">
        <?php $_incl = $_item->getPriceInclTax(); ?>
        <span class="cart-price">
            <?php /* @escapeNotVerified */ echo $block->formatPrice($_incl * $unitConvert) ?>
        </span>
    </span>
<?php endif; ?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
        <span class="cart-price">
            <?php
            /* @escapeNotVerified */
            $_excl = $block->getItemDisplayPriceExclTax();
            echo $block->formatPrice($_excl * $unitConvert) ?>
        </span>
    </span>
<?php endif; ?>
