<?php
namespace Riki\GiftWrapping\Controller\Adminhtml\Giftwrapping;
/**
 * Class ChangeStatus
 * @package Riki\GiftWrapping\Controller\Adminhtml\Giftwrapping
 */
class ChangeStatus extends \Magento\GiftWrapping\Controller\Adminhtml\Giftwrapping\ChangeStatus
{
    /**
     * @var \Riki\GiftWrapping\Helper\GiftWrapping
     */
    protected $_giftwrappingHelper;

    /**
     * ChangeStatus constructor.
     * @param \Riki\GiftWrapping\Helper\GiftWrapping $giftWrapping
     * @param \Magento\Backend\App\Action\Context $context
     * @param \Magento\Framework\Registry $coreRegistry
     * @param \Magento\GiftWrapping\Model\ResourceModel\Wrapping $wrappingModelResource
     */
    public function __construct(
        \Riki\GiftWrapping\Helper\GiftWrapping $giftWrapping,
        \Magento\Backend\App\Action\Context $context,
        \Magento\Framework\Registry $coreRegistry,
        \Magento\GiftWrapping\Model\ResourceModel\Wrapping $wrappingModelResource
    )
    {
        $this->_giftwrappingHelper = $giftWrapping;
        parent::__construct($context, $coreRegistry, $wrappingModelResource);
    }

    public function execute()
    {
        $wrappingIds = (array)$this->getRequest()->getParam('wrapping_ids');
        $this->_giftwrappingHelper->createCsvChangeStatusAction($wrappingIds);
        return parent::execute(); // TODO: Change the autogenerated stub
    }
}
