<?php

namespace Riki\GiftWrapping\Controller\Adminhtml\Giftwrapping;

class MassDelete extends \Magento\GiftWrapping\Controller\Adminhtml\Giftwrapping\MassDelete
{
    /**
     * @var \Riki\GiftWrapping\Helper\GiftWrapping
     */
    protected $_giftwrappingHelper;
    
    public function __construct(
        \Riki\GiftWrapping\Helper\GiftWrapping $giftWrapping)
    {
        $this->_giftwrappingHelper = $giftWrapping;
    }

    public function execute()
   {
       $this->_giftwrappingHelper->createCsvDeleteAction();
       return parent::execute(); // TODO: Change the autogenerated stub
   }
}
