<?php


namespace Nestle\Migration\Model\DataMigration;


use Nestle\Migration\Model\DataMigration;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class DuplicateTable
 * @package Nestle\Migration\Model\DataMigration
 */
class DuplicateTable extends AbstractDataMigration
{
    /**
     *
     */
    const TABLE_DUPLICATE = [
        "default" => [
            "catalog_product_index_price",
            "catalogrule_product_price",
            "salesrule_coupon_aggregated_order"
        ]
    ];

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return AbstractDataMigration
     */
    public function run(InputInterface $input, OutputInterface $output)
    {
        $this->fixDuplicateTable($input, $output);
        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }

    /**
     * @param $input
     * @param $output
     */
    private function fixDuplicateTable($input, $output)
    {
        foreach (DuplicateTable::TABLE_DUPLICATE as $resource => $tables) {
            $adapter = $this->resourceConnection->getConnection($resource);
            DataMigration::info("fixing duplicate table");
            foreach ($tables as $table) {
                //$adapter->dropTable($adapter->getTableName($table));
            }
        }
    }
}
