<?php


namespace Nestle\Migration\Model\DataMigration;


use Magento\Eav\Setup\EavSetup;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Setup\Declaration\Schema\Sharding;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Nestle\Migration\Model\DataMigration;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Magento\Eav\Setup\EavSetupFactory;

/**
 * Class UpdateManufactureAttribute
 * @package Nestle\Migration\Model\DataMigration
 */
class UpdateManufactureAttribute extends AbstractDataMigration
{

    /**
     * @var EavSetupFactory
     */
    private $eavSetupFactory;
    /**
     * @var ModuleDataSetupInterface
     */
    private $moduleDataSetup;

    /**
     * UpdateManufactureAttribute constructor.
     * @param Sharding $sharding
     * @param ResourceConnection $resourceConnection
     * @param EavSetupFactory $eavSetupFactory
     */
    public function __construct(
        Sharding $sharding,
        ResourceConnection $resourceConnection,
        EavSetupFactory $eavSetupFactory,
        ModuleDataSetupInterface $moduleDataSetup
    )
    {
        $this->eavSetupFactory = $eavSetupFactory;
        $this->moduleDataSetup = $moduleDataSetup;
        parent::__construct($sharding, $resourceConnection);
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return AbstractDataMigration
     */
    public function run(InputInterface $input, OutputInterface $output)
    {
        if ($input->getOption(DataMigration::OPTION_MIGRATION_FIX_CONFIGURABLE_PRODUCT) !== false) {
            DataMigration::info("fixing incompatible configurable product patch");
            /** @var EavSetup $eavSetup */
            $eavSetup = $this->eavSetupFactory->create(['setup' => $this->moduleDataSetup]);
            $eavSetup->updateAttribute(\Magento\Catalog\Model\Product::ENTITY, 'manufacturer', 'apply_to', "simple,configurable");
        }

        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }
}
