<div id="add-another-course-popup">
    <div class="subscription-container free-html">
        <p><img width="100%" style="display: block" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/free_html_muti_course.jpg') ?>" alt="あなたのほっとするひと時と笑顔の" /></p>
    </div>
    <div class="note"><?php echo __('Please select products from the following.') ?></div>
    <div class="subscription-container">
        <input type="checkbox" class="toggle-checkbox" id="subscription-container-block-1">
        <div class="category-title">
            <h2>キットカット地域限定商品</h2>
            <label for="subscription-container-block-1" class="triangle-toggle"></label>
        </div>
        <div class="subscription-content">
            <table class="subscription-table">
                <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th class="col name"><?php echo __('Product name') ?></th>
                    <th data-bind="i18n: 'Item price (tax incl)'" class="col price"><?php echo __('Item price (tax incl)') ?></th>
                    <th data-bind="i18n: 'Qty'" class="col qty"><?php echo __('Qty') ?></th>
                    <th class="col price subtotal"><?php echo __('Subtotal (tax incl)') ?></th>
                </tr>
                </thead>
                <tbody>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="subscription-container">
        <input type="checkbox" class="toggle-checkbox" id="subscription-container-block-2">
        <div class="category-title">
            <h2>キットカット地域限定商品</h2>
            <label for="subscription-container-block-2" class="triangle-toggle"></label>
        </div>
        <div class="subscription-content">
            <table class="subscription-table">
                <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th class="col name"><?php echo __('Product name') ?></th>
                    <th data-bind="i18n: 'Item price (tax incl)'" class="col price"><?php echo __('Item price (tax incl)') ?></th>
                    <th data-bind="i18n: 'Qty'" class="col qty"><?php echo __('Qty') ?></th>
                    <th class="col price subtotal"><?php echo __('Subtotal (tax incl)') ?></th>
                </tr>
                </thead>
                <tbody>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="subscription-container">
        <input type="checkbox" class="toggle-checkbox" id="subscription-container-block-3">
        <div class="category-title">
            <h2>キットカット地域限定商品</h2>
            <label for="subscription-container-block-3" class="triangle-toggle"></label>
        </div>
        <div class="subscription-content">
            <table class="subscription-table">
                <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th class="col name"><?php echo __('Product name') ?></th>
                    <th data-bind="i18n: 'Item price (tax incl)'" class="col price"><?php echo __('Item price (tax incl)') ?></th>
                    <th data-bind="i18n: 'Qty'" class="col qty"><?php echo __('Qty') ?></th>
                    <th class="col price subtotal"><?php echo __('Subtotal (tax incl)') ?></th>
                </tr>
                </thead>
                <tbody>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                <tr class="item">
                    <td class="col image">
                        <a href="#" class="product-item-photo"><img class="product-image-photo" src="http://10.87.1.143/riki/pub/static/frontend/Riki/default/ja_JP/Magento_Catalog/images/product/placeholder/small_image.jpg" alt="Product A"></a>
                    </td>
                    <td class="col name">
                        <input type="hidden" name="data[product][354_155][product_id]" value="354">
                        <div class="product-item-name">
                            <a href="http://10.87.1.143/riki/ec/product-a5.html">Product A</a>
                            <div class="notification-qty instock-threshold"><span>在庫: ご注文受付中。</span></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Item price (tax incl)') ?>" class="col price">9,721円</td>
                    <td data-th="<?php echo __('Qty') ?>" class="col qty">
                        <div>
                            <label class="label no-display" for="qty_354_155" data-bind="i18n: 'Qty'"></label>
                            <div class="control qty select-wrapper">
                                <select class="input-new select-box">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                </select>
                            </div>
                            <div class="unit-label" data-bind="i18n: 'Piece'"></div>
                        </div>
                    </td>
                    <td data-th="<?php echo __('Subtotal (tax incl)') ?>" class="col price subtotal ">9,721円</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="total-amount-block">
        <table class="table table-total-amount">
            <tr>
                <td class="mask" data-label="<?php echo $block->escapeHtml(__('(Incl. Tax)')); ?>"><?php echo __('Total Amount') ?></td>
                <td class="value" id="total-amount">0円</td>
            </tr>
        </table>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" data-title="<?php echo __('Put In Cart') ?>" class="tracking-floating-button action submit primary tocart" title="<?php echo __('Add to Cart') ?>"><span><?php echo __('Add to Cart') ?></span></button>
        </div>
        <div class="secondary"><a data-title="<?php echo __('Go Back to Previous Page') ?>" class="tracking-floating-button action back" href="javascript:void(0)" onclick="history.back();"><span><?php echo __('Go back') ?></span></a></div>
    </div>
</div>