<?php
$items = $block->getItems();
$image = 'swatch_image';
?>
<?php if (!empty($items) && is_array($items)) : ?>
    <div class="wrapper">
        <div class="label"><?php echo __('Variation products'); ?></div>
        <ul class="products">
            <?php foreach ($items as $_item):  ?>
                <?php $dataImage = $block->getGalleryImages($_item);?>
                <?php if ($_item->isSaleable()) : ?>
                    <li data-item-id="<?php echo $_item->getSku();?>">
                        <?php if($dataImage): ?>
                        <a  layer-item-id="<?php echo $_item->getId();?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <img class="product-image-photo" src="<?php echo $dataImage['url'] ?>" alt="<?php echo $dataImage['label'];?>"/>
                        </a>
                        <span class="label-swatch"><?php echo $dataImage['label'];?></span>
                        <?php else:?>
                        <a  layer-item-id="<?php echo $_item->getId();?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->getImage($_item, $image)->toHtml();?>
                        </a>
                        <?php endif;?>
                    </li>
                <?php else: ?>
                    <li>
                        <?php if($dataImage): ?>
                            <img class="product-image-photo" src="<?php echo $dataImage['url'] ?>" alt="<?php echo $dataImage['label'];?>"/>
                            <span class="label-swatch"><?php echo $dataImage['label'];?></span>
                        <?php else:?>
                            <?php echo $block->getImage($_item, $image)->toHtml();?>
                        <?php endif;?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif;?>
