<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php $options = $block->decorateArray($block->getOptions()); ?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
        <script type="text/x-magento-init">
            {
                "#form-validate": {
                    "Riki_SubscriptionPage/js/price-bundle-custom": {
                        "optionConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>,
                        "priceBoxSelector": ".subscription-info-price<?php echo $product->getId() ?> .price-box",
                        "controlContainer": ".field.option"
                    }
                }
            }
        </script>
        <fieldset class="fieldset fieldset-bundle-options">
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?php echo $block->getOptionHtml($option) ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?php /* @escapeNotVerified */ echo __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
