<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Sales\Model\Order\Shipment\Item $_item */
$_item = $block->getItem();

/** @var \Magento\Sales\Model\Order\Item $orderItem */
$orderItem = $_item->getOrderItem()
?>
<tr class="border">
    <td class="col-product"><?php echo $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-subtotal"><?php echo $orderItem->getOrder()->formatPrice($orderItem->getPriceInclTax() * $_item->getQty()) ?></td>

        <?php
            if('CS' == $_item->getUnitCase()){ ?>
                <td class="col-qty"><?php /* @escapeNotVerified */ echo $_item->getQty()*1/((null != $_item->getUnitQty())?$_item->getUnitQty():1) ?><?php
                echo ' ('.(__($_item->getUnitCase()).' ('.$_item->getUnitQty().' '.__('EA')).'))';
            ?></td><?php
            }
            else{ ?>
                <td class="col-qty"><?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?><?php
                echo ' ('.((null != $_item->getUnitCase())?__($_item->getUnitCase()):__('EA')).')';
            ?></td><?php
            }
        ?>
    <td class="col-commission_amount last"><?php echo $orderItem->getOrder()->formatPrice($_item->getCommissionAmount()); ?></td>
</tr>
