<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $_item->setStoreId($_item->getCreditMemo()->getStoreId()) ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <td class="col-product"><?php echo $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-price">
        <?php echo $block->getColumnHtml($_item, 'price'); ?>
    </td>
    <?php
    if('CS' == $_item->getUnitCase()){ ?>
        <td class="col-qty"><?php /* @escapeNotVerified */ echo $_item->getQty()*1/((null != $_item->getUnitQty())?$_item->getUnitQty():1) ?><?php
        echo ' ('.(__($_item->getUnitCase()).' ('.$_item->getUnitQty().' '.__('EA')).'))';
        ?></td><?php
    }
    else{ ?>
        <td class="col-qty"><?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?><?php
        echo ' ('.((null != $_item->getUnitCase())?__($_item->getUnitCase()):__('EA')).')';
        ?></td><?php
    }
    ?>
    <td class="col-subtotal">
        <?php echo $block->getColumnHtml($_item, 'subtotal'); ?>
    </td>
    <td class="col-tax"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discount"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?php echo $block->getColumnHtml($_item, 'total'); ?>
    </td>
</tr>
