<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php

$allProductCartItems = $block->getListProductItem();
$exitItem =  (count($allProductCartItems)>0) ? true : false;
$exitSubscriptionHanpukai = $block->checkShowRelatedProduct();

$type = 'related';
$class = $type;
$image = 'related_products_list';
$title = __('Related Products');
$limit = 0;
$shuffle = 0;
$showWishlist = false;
$showCompare = false;
$showCart = true;
$templateType = null;
$description = false;
$canItemsAddToCart = false;
$showOwlCarousel = true;
$items = $allProductCartItems;
$limit = 0;
$shuffle = 0;

?>

<?php if ($exitItem && !$exitSubscriptionHanpukai):?>
<?php if ($items): ?>

<div class="block additional-cart">
    <?php if ($type == 'related' || $type == 'upsell'): ?>
    <div class="block-additional-products">
        <?php if ($type == 'related'): ?>
        <div class="banner">
            <img class="pc" src="<?php echo $block->getViewFileUrl('Riki_Checkout::images/related-prod-banner.png'); ?>" alt="Banner for Relates Product"/>
            <img class="sp" src="<?php echo $block->getViewFileUrl('Riki_Checkout::images/related-prod-banner-mobile.jpg'); ?>" alt="Banner for Relates Product"/>
        </div>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
            <?php else: ?>

            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
                <?php endif; ?>
                <?php else: ?>
                <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
                    <?php endif; ?>
                    <div class="block-title title">
                        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
                    </div>
                    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
                        <?php if ($type == 'related' && $canItemsAddToCart): ?>
                            <div class="block-actions">
                                <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
                                <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
                            </div>
                        <?php endif; ?>
                        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                            <ol class="products list items product-items <?php if ($showOwlCarousel): ?> owl-carousel <?php endif; ?>">
                                <?php $iterator = 1; ?>
                                <?php foreach ($items as $_item): ?>
                                    <?php if($_item->isSaleable()): ?>
                                        <?php $available = ''; ?>
                                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                            <?php if (!$_item->getRequiredOptions()): ?>
                                                <?php $available = 'related-available'; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if ($type == 'related' || $type == 'upsell'): ?>
                                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                                        <?php else: ?>
                                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                                        <?php endif; ?>
                                        <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                            </a>
                                            <div class="product details product-item-details">
                                                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                        <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                                </strong>

                                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                                <?php if ($templateType): ?>
                                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                                <?php endif; ?>

                                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                                    <?php if (!$_item->getRequiredOptions()): ?>
                                                        <div class="field choice related">
                                                            <?php if ($canItemsAddToCart) : ?>
                                                                <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                                            <?php endif; ?>
                                                            <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>

                                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                                    <div class="product actions product-item-actions">
                                                        <?php if ($showCart): ?>
                                                            <div class="actions-primary">
                                                                <?php if ($_item->isSaleable()): ?>

                                                                    <input type="number" name="qty" maxlength="3" value="1" class="input-text qty">

                                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                            <span data-label="<?php echo __('Buy') ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></span>
                                                                        </button>
                                                                    <?php else: ?>
                                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                        ?>
                                                                        <button class="action tocart primary"
                                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                            <span data-label="<?php echo __('Buy') ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></span>
                                                                        </button>
                                                                    <?php endif; ?>
                                                                <?php else: ?>
                                                                    <?php if ($_item->getIsSalable()): ?>
                                                                        <input type="number" name="qty" maxlength="3" value="1" class="input-text qty">
                                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                                    <?php else: ?>
                                                                        <input type="number" name="qty" maxlength="3" value="1" class="input-text qty">
                                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                                    <?php endif; ?>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>

                                                        <?php if ($showWishlist || $showCompare): ?>
                                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                                    </a>
                                                                <?php endif; ?>
                                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                    <?php
                                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                                    ?>
                                                                    <a href="#" class="action tocompare"
                                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                                       data-role="add-to-links"
                                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                                    </a>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>

                                    <?php endif; ?>

                                <?php endforeach ?>

                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                require([
                    'jquery',
                    'Magento_Catalog/js/owl.carousel'
                ], function($) {
                    $(document).ready(function () {
                        var inputQtyAddCart = $('.block-additional-products .qty'),
                            addButton = $('.block-additional-products .action.tocart');
                        inputQtyAddCart.on('change',function () {
                            var qty = $(this).val();
                            var dataPost = JSON.parse($(this).next('.tocart').attr('data-post'));
                            dataPost.data.qty = qty;
                            $(this).next('.tocart').attr('data-post', JSON.stringify(dataPost));
                        });
                        addButton.on('click', function () {
                            var _this = $(this),
                                qty = _this.prev('.qty').val();
                            if(isNaN(qty) || qty <= 0)
                                return false;
                        });

                        <?php if ($showOwlCarousel): ?>
                        var owl = $(".owl-carousel");
                        owl.owlCarousel({
                            items: 5,
                            mouseDrag: true,
                            touchDrag: true,
                            margin: 15,
                            nav: false,
                            dots: false,
                            responsiveClass:true,
                            responsive: {
                                680: {
                                    items: 4
                                },
                                880: {
                                    items: 4
                                }
                            }
                        });
                        <?php endif; ?>
                    });
                });
            </script>
        </div>
        <?php endif;?>
    <?php endif;?>
