<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function($){
        var rulesAA = {
            "validate-time-24-hour": [
                function (value) {
                    return /^([2][0-3]|[01]?[0-9])([.:][0-5][0-9])?$/.test(value);
                },
                '<?php echo __('Time input is invalid (00:00 -> 23:59)') ?>'
            ]
        }
        $.each(rulesAA, function (i, rule) {
            rule.unshift(i);
            $.validator.addMethod.apply($.validator, rule);
        });

    });
</script>
