<?php /** @var \Riki\Coupons\Block\SecretUrlCoupon $block */ ?>
<script>
    require(
        [
            'jquery',
            'Magento_Customer/js/customer-data',
            'Magento_Ui/js/model/messageList',
            'mage/translate'
        ],
        function (
            $,
            customerData,
            messageList
        ) {
            'use strict';

            var getUrlParameter = function(name) {
                name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
                var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
                var results = regex.exec(location.search);
                return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
            };
            var cookieConfig = {
                domain: '<?php echo $block->getCookieDomain() ?>',
                path: '<?php echo $block->getCookiePath() ?>',
                secure: ('<?php echo $block->getCookieSecure() ?>' === 'true')
            };
            var coupon = getUrlParameter('coupon'),
                campaignId = getUrlParameter('campaign_id'),
                errorMsg = '';

            if (campaignId) {
                if (campaignId.length !== 7) {
                    errorMsg = '<?php echo __('Campaign Id is invalid. Campaign Id must have 7 digits.') ?>';
                    campaignId = null;
                } else if (!campaignId.match(/^[A-Za-z0-9_]{7}$/)) {
                    errorMsg = '<?php echo __('Campaign Id is invalid. Campaign ID must be alphanumeric character') ?>';
                    campaignId = null;
                }
            }

            if (coupon) {
                $.cookie('<?php echo \Riki\Coupons\Observer\SecretUrlCouponObserver::COUPON ?>', coupon, cookieConfig);
            }
            if (campaignId) {
                $.cookie('<?php echo \Riki\Coupons\Observer\SecretUrlCouponObserver::CAMPAIGN_ID ?>', campaignId, cookieConfig);
            }

            if (errorMsg) {
                var messageWrapper = $('#maincontent').find('.page.messages'),
                    checkoutWrapper = $('#checkout');
                if (messageWrapper.length) {
                    var messages = customerData.get('messages').extend({disposableCustomerData: 'messages'})();
                    if (!messages.hasOwnProperty('messages')) {
                        messages.messages = [];
                    }
                    messages.messages.push({
                        type: 'error',
                        text: errorMsg
                    });
                    customerData.get('messages')
                        .extend(
                            {disposableCustomerData: 'messages'}
                        )(messages);
                } else if (checkoutWrapper.length) {
                    messageList.addErrorMessage(
                        {'message': errorMsg}
                    );
                }
            }
        }
    );

</script>