<?php
namespace Riki\Subscription\Block\Adminhtml\Order\Create\Course;

use Magento\Framework\View\Element\Template;
class Frequency extends Template
{
    /**
     * @var \Riki\Subscription\Helper\Hanpukai\Data
     */
    protected $_helperHanpukai;
    /**
     * Session quote
     *
     * @var \Magento\Backend\Model\Session\Quote
     */
    protected $_sessionQuote;


    public function __construct(
        Template\Context $context,
        \Riki\Subscription\Helper\Hanpukai\Data $helperHanpukai,
        \Magento\Backend\Model\Session\Quote $quote,
        array $data = []
    )
    {
        $this->_helperHanpukai = $helperHanpukai;
        $this->_sessionQuote = $quote;
        parent::__construct($context, $data);
    }
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    public function getFrequency()
    {
        $courseId = $this->getRequest()->getParam('id');
        $subCourseHelperData = $this->_helperHanpukai->getSubscriptionCourseHelperData();
        $frequency = $subCourseHelperData->getFrequenciesByCourse($courseId);
        return $frequency;
    }

    public function getFrequencyId()
    {
        return $this->_request->getParam('frequency_id');
    }

    public function isHanpukai(){
        $courseId = $this->getRequest()->getParam('id');
        $subscriptonCourseType = $this->_helperHanpukai->getSubscriptionCourseType($courseId);
        if($subscriptonCourseType=='hanpukai'){
            return true;
        }
        return false;
    }
    /**
     * Get frequency selected on previous time
     *
     * @return bool|mixed
     */
    public function getFrequencySelected(){
        $request = $this->_sessionQuote->getQuote();
        if($request->getData('riki_frequency_id')){
            return $request->getData('riki_frequency_id');
        }
        return false;
    }
}