<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
USAGE:

Simple:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->toHtml() ?>

For checkout/onepage/shipping.phtml:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->setFieldIdFormat('shipping:%s')
   ->setFieldNameFormat('shipping[%s]')
   ->setFieldParams('onchange="shipping.setSameAsBilling(false);"')
   ->toHtml() ?>
*/
/* @var $block \Magento\Customer\Block\Widget\Name */
$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
$addressId = $block->getObject()->getId();
?>

<?php if ($prefix || $middle || $suffix && !$block->getNoWrap()): ?>
<div class="field required fullname <?php /* @escapeNotVerified */ echo $block->getContainerClassName() ?>">
    <label for="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>" class="label">
        <span><?php /* @escapeNotVerified */ echo __('Name') ?></span>
    </label>
    <div class="control">
        <fieldset class="fieldset fieldset-fullname">
        <div class="fields">
<?php endif; ?>

    <?php if ($prefix): ?>
        <div class="field field-name-prefix<?php if ($block->isPrefixRequired()) echo ' required' ?>">
            <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>">
                <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('prefix') ?></span>
            </label>

            <div class="control">
                <?php if ($block->getPrefixOptions() === false): ?>
                    <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
                           name="<?php /* @escapeNotVerified */ echo $block->getFieldName('prefix') ?>"
                           value="<?php echo $block->escapeHtml($block->getObject()->getPrefix()) ?>"
                           title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('prefix') ?>"
                           class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?>>
                <?php else: ?>
                    <select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
                            name="<?php /* @escapeNotVerified */ echo $block->getFieldName('prefix') ?>"
                            title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('prefix') ?>"
                            class="<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
                        <?php foreach ($block->getPrefixOptions() as $_option): ?>
                            <option value="<?php /* @escapeNotVerified */ echo $_option ?>"<?php if ($block->getObject()->getPrefix() == $_option): ?> selected="selected"<?php endif; ?>>
                                <?php /* @escapeNotVerified */ echo __($_option) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
        <div class="field field-name required">
            <label class="label" attr-have-to="<?php /* @escapeNotVerified */ echo __('Have to') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Register name') ?></span>
            </label>

            <div class="control">
                <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>"
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('lastname') ?>"
                       <?php if($addressId): ?>
                       value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
                       <?php endif; ?>
                       maxlength="25"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>"
                       class="input-text required-entry-last-name validate_double_byte_last_name max_text_length" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>>
                <div class="field-tips"><?php echo __('Example: Yamada') ?></div>
            </div>

            <div class="control">
                <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>"
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('firstname') ?>"
                        <?php if($addressId): ?>
                       value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
                        <?php endif; ?>
                       maxlength="25"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>"
                       class="input-text required-entry-first-name validate_double_byte_first_name max_text_length" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>>
                <div class="field-tips"><?php echo __('Example: Taro') ?></div>
            </div>
        </div>

        <!--Custom katakana name-->
        <div class="field field-name required">
            <label class="label" attr-have-to="<?php /* @escapeNotVerified */ echo __('Have to') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Name in katakana') ?></span>
            </label>
            <?php
            $lastnameKana = $block->getObject()->getCustomAttribute('lastnamekana');
            if ($lastnameKana) {
                $lastnameKana = $lastnameKana->getValue();
            }else {
                $lastnameKana = '';
            }
            ?>
            <div class="control">
                <input type="text" id="lastnamekana"
                       name="lastnamekana"
                        <?php if($addressId): ?>
                       value="<?php echo $block->escapeHtml($lastnameKana) ?>"
                       <?php endif; ?>
                       maxlength="40"
                       title="<?php /* @escapeNotVerified */ echo __('Last name katakana') ?>"
                       class="input-text required-entry-last-name-katakana validate_double_byte_last_kanatana_name max_text_length">
                <div class="field-tips"><?php echo __('Example: Katakana Yamada') ?></div>
            </div>

            <?php
            $fristnameKana = $block->getObject()->getCustomAttribute('firstnamekana');
            if ($fristnameKana) {
                $fristnameKana = $fristnameKana->getValue();
            }else {
                $fristnameKana = '';
            }
            ?>
            <div class="control">
                <input type="text" id="firstnamekana"
                       name="firstnamekana"
                        <?php if($addressId): ?>
                       value="<?php echo $block->escapeHtml($fristnameKana) ?>"
                       <?php endif; ?>
                       title="<?php /* @escapeNotVerified */ echo __('First name katakana') ?>"
                       maxlength="40"
                       class="input-text validate_double_byte_first_kanatana_name required-entry-first-name-katakana max_text_length">
                <div class="field-tips"><?php echo __('Example: Katakana Taro') ?></div>
            </div>
        </div>

    <?php if ($middle): ?>
        <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
        <div class="field field-name-middlename<?php echo $isMiddlenameRequired ? ' required' : '' ?>">
            <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId('middlename') ?>">
                <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('middlename') ?></span>
            </label>

            <div class="control">
                <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('middlename') ?>"
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('middlename') ?>"
                       value="<?php echo $block->escapeHtml($block->getObject()->getMiddlename()) ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('middlename') ?>"
                       class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('middlename') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php echo $isMiddlenameRequired ? ' data-validate="{required:true}"' : '' ?>>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($suffix): ?>
        <div class="field field-name-suffix<?php if ($block->isSuffixRequired()) echo ' required' ?>">
            <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId('suffix') ?>">
                <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('suffix') ?></span>
            </label>

            <div class="control">
                <?php if ($block->getSuffixOptions() === false): ?>
                    <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('suffix') ?>"
                           name="<?php /* @escapeNotVerified */ echo $block->getFieldName('suffix') ?>"
                           value="<?php echo $block->escapeHtml($block->getObject()->getSuffix()) ?>"
                           title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('suffix') ?>"
                           class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('suffix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>>
                <?php else: ?>
                    <select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('suffix') ?>"
                            name="<?php /* @escapeNotVerified */ echo $block->getFieldName('suffix') ?>"
                            title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('suffix') ?>"
                            class="<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('suffix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>>
                        <?php foreach ($block->getSuffixOptions() as $_option): ?>
                            <option value="<?php /* @escapeNotVerified */ echo $_option ?>"<?php if ($block->getObject()->getSuffix() == $_option): ?> selected="selected"<?php endif; ?>>
                                <?php /* @escapeNotVerified */ echo __($_option) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($prefix || $middle || $suffix && !$block->getNoWrap()): ?>
            </div>
        </fieldset>
    </div>
</div>
<?php endif; ?>
