<p class="method-notice"><?php echo __('Please enter card information from the Go to Enter Card Information on the next page') ?></p>
<p><img src="<?php echo $block->getViewFileUrl('images/credit_card_method.png'); ?>" alt=" Image Card Method"></p>
<div><?php echo __('Points to remember about credit card with debit function'); ?></div>
<div><?php echo __('Credit card with debit function will be withdrawn when card information is entered.~'); ?></div>