<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Items\Grid
 */
?>

<?php
/** @var \Riki\Sales\Helper\Admin $helper */
$helper = $this->helper('Riki\Sales\Helper\Admin');

/** @var \Riki\Promo\Helper\Data $_promoHelper */
$_promoHelper = $this->helper('Riki\Promo\Helper\Data');

/** @var \Riki\Subscription\Helper\Adminhtml\Data $subHelper */
$subHelper = $this->helper('Riki\Subscription\Helper\Adminhtml\Data');
$machineHelper = $this->helper('Riki\MachineApi\Helper\Machine');
$courseName = $subHelper->getCourseNameByCurrentQuote();
$courseType = $subHelper->getCourseTypeByCurrentQuote();
$frequency = $subHelper->getFrequencyNameByCurrentQuote();
?>
<?php $isMultipleAddress = $helper->isMultipleShippingAddressCart(); ?>
<?php $isAllowedCustomPrice = $helper->isAllowedToCustomCreateOrderItemPrice(); ?>

<?php $_items = $block->getItems() ?>
<?php if (empty($_items)): ?>
    <div id="order-items_grid">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary order-tables">
                <thead>
                    <tr class="headings">
                        <?php if($courseName): ?>
                        <th class="col-course"><span><?php /* @escapeNotVerified */ echo __('Subscription Course') ?></span></th>
                        <th class="col-frequency"><span><?php /* @escapeNotVerified */ echo __('Frequency') ?></span></th>
                        <?php endif; ?>
                        <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                        <th class="col-price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                        <th class="col-qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                        <th class="col-subtotal"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                        <th class="col-discount"><span><?php /* @escapeNotVerified */ echo __('Discount') ?></span></th>
                        <th class="col-row-total"><span><?php /* @escapeNotVerified */ echo __('Row Subtotal') ?></span></th>
                        <?php if($isMultipleAddress): ?>
                            <th class="col-address"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></th>
                        <?php endif; ?>
                        <th class="col-action"><span><?php /* @escapeNotVerified */ echo __('Action') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100"><?php /* @escapeNotVerified */ echo __('No ordered items') ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php else: ?>
    <?php $totalItem = count($_items); ?>
    <div class="admin__table-wrapper" id="order-items_grid">
    <?php if ($totalItem>10): ?>
        <div class="actions update actions-update">
        <?php if($isMultipleAddress): ?>
            <?php echo $block->getButtonHtml(__('Update Items and Quantities and Addresses'), 'order.itemsUpdate()', 'action-secondary'); ?>
            <?php else: ?>
                <?php echo $block->getButtonHtml(__('Update Items and Quantities'), 'order.itemsUpdate()', 'action-secondary'); ?>
                <?php if($courseType == \Riki\SubscriptionCourse\Model\Course\Type::TYPE_MULTI_MACHINES): ?>
                    <?php echo $block->getButtonHtml(__('Select Multiple Machines'), 'addBySku.openGridMachineTypes()', 'action-secondary'); ?>
                <?php endif; ?>
        <?php endif; ?>
            </div>
    <?php endif; ?>
        <table class="data-table admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <?php if($courseName): ?>
                        <th class="col-course"><span><?php /* @escapeNotVerified */ echo __('Subscription Course') ?></span></th>
                        <th class="col-frequency"><span><?php /* @escapeNotVerified */ echo __('Frequency') ?></span></th>
                    <?php endif; ?>
                    <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                    <th class="col-price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                    <th class="col-qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                    <th class="col-subtotal"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                    <th class="col-discount"><span><?php /* @escapeNotVerified */ echo __('Discount') ?></span></th>
                    <th class="col-row-total"><span><?php /* @escapeNotVerified */ echo __('Row Subtotal') ?></span></th>
                    <?php if($isMultipleAddress): ?>
                        <th class="col-address"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></th>
                    <?php endif; ?>
                    <th class="col-action"><span><?php /* @escapeNotVerified */ echo __('Action') ?></span></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <?php if($courseName): ?>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    <?php endif; ?>
                    <td class="col-total"><?php /* @escapeNotVerified */ echo __('Total %1 product(s)', count($_items)) ?></td>
                    <td colspan="2" class="col-subtotal"><?php /* @escapeNotVerified */ echo __('Subtotal:') ?></td>
                    <td class="col-price"><strong><?php /* @escapeNotVerified */ echo $block->formatPrice($block->getSubtotal()) ?></strong></td>
                    <td class="col-price"><strong><?php /* @escapeNotVerified */ echo $block->formatPrice($block->getDiscountAmount()) ?></strong></td>
                    <td class="col-price"><strong>
                    <?php
                        /* @escapeNotVerified */ echo $block->formatPrice($block->getSubtotalWithDiscount());
                    ?></strong></td>
                    <td colspan="2">&nbsp;</td>
                </tr>
            </tfoot>
                <?php $i = 0 ?>
            <tbody>
                <?php foreach ($_items as $_item):$i++ ?>
                    <?php if ($_item->getData('prize_id')) : continue; endif ;?>
                    <?php $_isPromoItem = $_promoHelper->isPromoItem($_item); ?>

                    <tr class="<?php /* @escapeNotVerified */ echo($i%2) ? 'even' : 'odd' ?>">
                        <?php if($courseName && $i== 1): ?>
                            <td class="col-course" rowspan="<?php echo $totalItem * 3; ?>">
                                <span><?php /* @escapeNotVerified */ echo $courseName; ?></span>
                            </td>
                            <td class="col-frequency" rowspan="<?php echo $totalItem *3; ?>">
                                <span><?php /* @escapeNotVerified */ echo $frequency; ?></span>
                            </td>
                        <?php endif; ?>
                        <td class="col-product <?php echo ($courseName && $i > 1) ? 'has-padding-left' : '' ?>">
                            <span id="order_item_<?php /* @escapeNotVerified */ echo $_item->getId() ?>_title"><?php echo $block->escapeHtml($_item->getName()) ?></span>
                            <div class="product-sku-block">
                                <span><?php /* @escapeNotVerified */ echo __('SKU') ?>:</span>
                                <?php echo implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))); ?>
                            </div>
                            <div class="product-configure-block">
                                <?php echo $block->getConfigureButtonHtml($_item) ?>
                            </div>
                        </td>
                        <td class="col-price">

                            <?php echo $block->getItemUnitPriceHtml($_item); ?>

                            <?php $_isCustomPrice = $block->usedCustomPriceForItem($_item) ?>
                            <?php if ($_tier = $block->getTierHtml($_item)): ?>
                            <div id="item_tier_block_<?php /* @escapeNotVerified */ echo $_item->getId() ?>"<?php if ($_isCustomPrice): ?> style="display:none"<?php endif; ?>>
                                <a href="#" onclick="$('item_tier_<?php /* @escapeNotVerified */ echo $_item->getId() ?>').toggle();return false;"><?php /* @escapeNotVerified */ echo __('Tier Pricing') ?></a>
                                <div style="display:none" id="item_tier_<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><?php /* @escapeNotVerified */ echo $_tier ?></div>
                            </div>
                            <?php endif; ?>
                            <?php if($isAllowedCustomPrice): ?>
                            <?php if ($block->canApplyCustomPrice($_item)): ?>
                                <div class="custom-price-block">
                                    <input type="checkbox"
                                           class="admin__control-checkbox"
                                           id="item_use_custom_price_<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                           <?php if ($_isCustomPrice): ?> checked="checked"<?php endif; ?>
                                           onclick="order.toggleCustomPrice(this, 'item_custom_price_<?php /* @escapeNotVerified */ echo $_item->getId() ?>', 'item_tier_block_<?php /* @escapeNotVerified */ echo $_item->getId() ?>');"/>
                                    <label
                                        class="normal admin__field-label"
                                        for="item_use_custom_price_<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('Custom Price') ?>*</span></label>
                                </div>
                            <?php endif; ?>
                            <input id="item_custom_price_<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                   name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][custom_price]"
                                   value="<?php /* @escapeNotVerified */ echo sprintf("%.2f", $block->getOriginalEditablePrice($_item))?>"
                                   <?php if (!$_isCustomPrice): ?>
                                   style="display:none"
                                   disabled="disabled"
                                   <?php endif; ?>
                                   class="input-text item-price admin__control-text"/>
                            <?php endif; ?>
                        </td>

                        <?php if('CS' == $_item->getData('unit_case')) { ?>

                            <td class="col-qty">
                                <input name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty_case]"
                                       productcartid="<?php echo $_item->getId();?>"
                                       unitqty="<?php echo ((null != $_item->getData('unit_qty'))?$_item->getData('unit_qty'):1);?>"
                                       class="input-text item-qty admin__control-text qty_case"
                                       value="<?php /* @escapeNotVerified */ echo $_item->getQty()*1 / ((null != $_item->getData('unit_qty'))?$_item->getData('unit_qty'):1) ?>"
                                       maxlength="12"
                                    <?php if($_isPromoItem): ?> disabled <?php endif; ?>
                                    /> <?php echo __($_item->getData('unit_case')).' ('.$_item->getData('unit_qty').' '.__('EA').')';?>
                            </td>
                            <td class="col-qty" style="display: none;">
                                <input name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                                       id="product_id_order_grid_<?php echo $_item->getId();?>"
                                       class="input-text item-qty admin__control-text"
                                       value="<?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>"
                                       maxlength="12"
                                    <?php if($_isPromoItem): ?> disabled <?php endif; ?>
                                    />
                            </td>

                        <?php }else{ ?>

                            <td class="col-qty">
                                <?php if ($_item->getIsRikiMachine()) : ?>
                                    1
                                    <input name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                                           value="1"
                                           type="hidden" />
                                <?php else : ?>
                                <input name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                                       class="input-text item-qty admin__control-text"
                                       value="<?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>"
                                       maxlength="12"
                                        <?php if($_isPromoItem): ?> disabled <?php endif; ?>
                                    />
                                <?php endif; ?>
                                <?php
                                    if('EA' == $_item->getData('unit_case')){
                                        echo __($_item->getData('unit_case'));
                                    }
                                ?>
                            </td>
                        <?php }?>

                        <td class="col-subtotal col-price">
                            <?php echo $block->getItemRowTotalHtml($_item); ?>
                        </td>
                        <td class="col-discount col-price">
                            <?php /* @escapeNotVerified */ echo $block->formatPrice(-$_item->getTotalDiscountAmount()) ?>
                            <?php if(!$_isPromoItem): ?>
                            <div class="discount-price-block">
                                <input id="item_use_discount_<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                       class="admin__control-checkbox"
                                       name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][use_discount]"
                                       <?php if (!$_item->getNoDiscount()): ?>checked="checked"<?php endif; ?>
                                       value="1"
                                       type="checkbox" />
                                <label
                                    for="item_use_discount_<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                    class="normal admin__field-label">
                                    <span><?php /* @escapeNotVerified */ echo __('Apply') ?></span></label>
                            </div>
                            <?php endif; ?>

                        </td>
                        <td class="col-price col-row-subtotal">
                            <?php echo $block->getItemRowTotalWithDiscountHtml($_item); ?>
                        </td>
                        <?php if($isMultipleAddress): ?>
                            <td class="col-address">
                                <?php echo $helper->getAddressListHtmlByCartItem($_item) ?>
                            </td>
                        <?php endif; ?>
                        <td class="col-actions last">
                            <?php if (!$_item->getIsRikiMachine()) : ?>
                                <?php if(!$_isPromoItem): ?>
                                <select class="admin__control-select" name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][action]">
                                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select') ?></option>
                                    <option value="remove"><?php /* @escapeNotVerified */ echo __('Remove') ?></option>
                                    <?php if ($block->getCustomerId() && $block->getMoveToCustomerStorage()): ?>
                                        <option value="cart"><?php /* @escapeNotVerified */ echo __('Move to Shopping Cart') ?></option>
                                        <?php if ($block->isMoveToWishlistAllowed($_item)): ?>
                                            <?php $wishlists = $block->getCustomerWishlists();?>
                                            <?php if (count($wishlists) <= 1):?>
                                                <option value="wishlist"><?php /* @escapeNotVerified */ echo __('Move to Wish List') ?></option>
                                            <?php else: ?>
                                                <optgroup label="<?php /* @escapeNotVerified */ echo __('Move to Wish List') ?>">
                                                    <?php foreach ($wishlists as $wishlist):?>
                                                        <option value="wishlist_<?php /* @escapeNotVerified */ echo $wishlist->getId();?>"><?php echo $block->escapeHtml($wishlist->getName());?></option>
                                                    <?php endforeach;?>
                                                </optgroup>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </select>
                                    <?php endif; ?>
                            <?php else: ?>
                                <input type="hidden" name="item[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][action]" value="" />
                            <?php endif; ?>
                        </td>
                    </tr>

                    <?php $hasMessageError = false; ?>
                    <?php foreach ($_item->getMessage(false) as $messageError):?>
                        <?php if (!empty($messageError)) {
                            $hasMessageError = true;
                        }
                        ?>
                    <?php endforeach; ?>

                    <?php if ($hasMessageError):?>
                        <tr class="row-messages-error">
                            <td colspan="100"> <!-- ToDo UI: remove the 100 -->
                                <?php foreach ($_item->getMessage(false) as $message):
                                    if (empty($message)) {
                                        continue;
                                    }
                                    ?>
                                    <div class="message <?php if ($_item->getHasError()): ?>message-error<?php else: ?>message-notice<?php endif; ?>">
                                        <?php echo $block->escapeHtml($message); ?>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif;?>

                    <?php echo $block->getItemExtraInfo($_item)->toHtml(); ?>

                <?php endforeach; ?>
                </tbody>
        </table>
        <p><small><?php /* @escapeNotVerified */ echo $block->getInclExclTaxMessage(); ?></small></p>
    </div>

    <div class="order-discounts">
        <?php if($isMultipleAddress): ?>
            <?php echo $block->getButtonHtml(__('Update Items and Quantities and Split Addresses'), 'order.itemsUpdate()', 'action-secondary'); ?>
            <?php echo $block->getButtonHtml(__('Update Items and Quantities and Combine Addresses'), 'order.itemsCombine()', 'action-secondary'); ?>
        <?php else: ?>
        <?php echo $block->getButtonHtml(__('Update Items and Quantities'), 'order.itemsUpdate()', 'action-secondary'); ?>
            <?php if($courseType == \Riki\SubscriptionCourse\Model\Course\Type::TYPE_MULTI_MACHINES): ?>
                <?php echo $block->getButtonHtml(__('Select Multiple Machines'), 'addBySku.openGridMachineTypes()', 'action-secondary'); ?>
            <?php endif; ?>
        <?php endif; ?>
        <div id="order-coupons" class="order-coupons"><?php echo $block->getChildHtml();?></div>
    </div>

    <script type="text/javascript">
        require([
            'jquery',
            'mage/mage'
        ], function ($) {
            'use strict';
            // check for change
            $('.qty_case').on('change',function(){
                var productcartid = $(this).attr('productcartid');
                var unitqty = $(this).attr('unitqty');
                $('#product_id_order_grid_'+productcartid).val($(this).val() * unitqty);
            });
        });
    </script>
    <script>
        require([
            'Magento_Sales/order/create/form'
        ], function(){
            order.itemsOnchangeBind()
        });
    </script>

<?php if ($block->isGiftMessagesAvailable()) : ?>
<script>
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }

    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);

    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;

//]]>

});
</script>
<?php endif; ?>
<?php endif; ?>
